// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 5.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_basic(c,a,b){this.go=function(d){b.find("ul").css("transform","translate3d(0,0,0)").stop(true).animate({left:(d?-d+"00%":(/Safari/.test(navigator.userAgent)?"0%":0))},c.duration,"easeInOutExpo");return d}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 5.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"basic",prev:"",next:"",duration:57*100,delay:26*100,width:960,height:360,autoPlay:true,playPause:true,stopOnHover:true,loop:false,bullets:0,caption:true,captionEffect:"move",controls:true,onBeforeStep:0,images:[{src:"./slider3.jpg",title:"slider3",descr:"sdfsdfsdfs",href:"sfsdfsdf"},{src:"./slider4.jpg",title:"slider4",descr:"sdfdsfds",href:"sdfsdf"},{src:"./slider6.jpg",title:"slider6",descr:"dsfsfsdf",href:"sdfsdf"}]});